### ISSUE TITLE
Not working with Pi 4b 8GB

### ISSUE THREAD

**Issue by ss9918** [SilentNightx/VitaDockPlus#6]
Tried this image with a Pi 4b 8gb model and just getting the 4 green flashes no boot, the Pi is good have tried with other images

**Comment by naifmeh** [comment]
Just tried on that same Pi, not working for me as well. No boot at all.

**Comment by ss9918** [comment]
Any solutions for Pi 4b 8GB?

**Comment by BeauJade** [comment]
Same issue here

**Comment by PasqualeMontone** [comment]
Any solution?

**Comment by PasqualeMontone** [comment]
Fixed with 1.2

**Comment by HelyeFab** [comment]
@PasqualeMontone 
Hi there, 
any chance you could share you managed to get it working on PI4 8gb. I have tried with version 1.2 and several sd card but to no avail. Any idea would be great!
CHEERS

**Comment by PasqualeMontone** [comment]
@HelyeFab 
On my p4 8gb the v1.2 works without any changes.

**Comment by dantesquivel** [comment]
I have also attempted v1.2 on RP4 and get a prompt to update the software. I was using the 
GeeekPi DeskPi Lite to output the signal (which has a "siter-board" with a power button and regular sized hdmi that connect through the usbc and micro hdmi), but I don't believe that's the problem since there was a signal output (hence the error promp) and the sd card is inserted in the RP4, not the "sister-board"

**Comment by SilentNightx** [comment]
Resolved in latest image.
